
import os

EMULATE=True

ALERT_NEW_DEVICE = True
ALERT_DOWN_DEVICE = True
ALERT_DOWN_THRESHOLD = 2
ALERT_FROM = 'test@example.com'
ALERT_SUBJECT=''
ALERT_TO =''
SMTP_SERVER = ''
SMTP_PORT = 589
SMTP_USERNAME = ''
SMTP_PASSWORD = ''
WEB_ADMIN_DEVICE_URL = ''